-- migrations/001-seed-tickets.sql
-- Insert 1..100 into tickets if not existing
BEGIN TRANSACTION;
INSERT OR IGNORE INTO tickets (numero, vendido, userId, fecha_creacion)
VALUES
-- Generated values
-- (will be generated by helper script if needed)
;
COMMIT;

-- Note: run the provided seed script which is idempotent and faster than long SQL lists.
